"""empty message

Revision ID: 45d5497fc024
Revises: 31d505e46568
Create Date: 2024-05-30 21:23:57.887157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45d5497fc024'
down_revision = '31d505e46568'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.BLOB(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.drop_column('content')

    # ### end Alembic commands ###
