"""make post entry_id nullable

Revision ID: 68aebd891f0d
Revises: d46898955e3e
Create Date: 2026-05-19 15:02:57.440299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68aebd891f0d'
down_revision = 'd46898955e3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('entry_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('entry_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
