"""move read length from posts to entries

Revision ID: 8df239896a75
Revises: e479c7a71b34
Create Date: 2026-05-28 12:30:11.798563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8df239896a75'
down_revision = 'e479c7a71b34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('read_length', sa.String(length=50), nullable=True))

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('read_length')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('read_length', sa.VARCHAR(length=150), nullable=True))

    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.drop_column('read_length')

    # ### end Alembic commands ###
