"""set read_length as an integer rather than a string

Revision ID: 926102bbdcec
Revises: 8df239896a75
Create Date: 2026-05-28 12:32:13.484198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '926102bbdcec'
down_revision = '8df239896a75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.alter_column('read_length',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.alter_column('read_length',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
