"""refactor posts and comments

Revision ID: d46898955e3e
Revises: 08b6206c3905
Create Date: 2026-05-19 14:54:16.174013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd46898955e3e'
down_revision = '08b6206c3905'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', sa.Integer(), nullable=False))
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_comments_post_id_posts', 'posts', ['post_id'], ['id'])
        batch_op.drop_column('entry_id')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('comments_enabled', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('comments_enabled')
        batch_op.drop_column('is_active')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entry_id', sa.INTEGER(), nullable=False))
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_comments_entry_id_entries', 'entries', ['entry_id'], ['id'])
        batch_op.drop_column('post_id')

    # ### end Alembic commands ###
