"""add post type and read length fields to posts

Revision ID: e479c7a71b34
Revises: d1056550ed9c
Create Date: 2026-05-27 14:54:23.860771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e479c7a71b34'
down_revision = 'd1056550ed9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('show_read_length', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('read_length', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('read_length')
        batch_op.drop_column('show_read_length')
        batch_op.drop_column('post_type')

    # ### end Alembic commands ###
