"""add is_featured to notebooks

Revision ID: ed51221efa9a
Revises: 98dd4ac8a2c3
Create Date: 2026-05-22 22:02:13.099195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed51221efa9a'
down_revision = '98dd4ac8a2c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notebooks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_featured', sa.Boolean(), nullable=False, server_default=sa.text('false')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notebooks', schema=None) as batch_op:
        batch_op.drop_column('is_featured')

    # ### end Alembic commands ###
